language: c
sudo: false
os:
    - linux

cache:
  directories:
    - $TRAVIS_BUILD_DIR/*/
    - $HOME/.elan

install:
  - |
    if [ ! -d "$HOME/.elan/toolchains/" ]; then
      curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain none -y
    fi
  - source ~/.elan/env
  - mkdir $HOME/scripts || echo ""
  - export PATH="$HOME/scripts:$PATH"
  - cp travis_long.sh $HOME/scripts/travis_long
  - chmod +x $HOME/scripts/travis_long
  - (git status | grep  -e "Changes not staged for commit:"); RESULT=$?
  - if [ $RESULT -eq 0 ]; then git checkout -f HEAD ; fi
  - git clean -d -f -q
  - ./purge_olean.sh
  - rm mathlib.txt || true

jobs:
  include:
    - stage: Pre-build-1
      script:
        - travis_long "timeout 2400 leanpkg test" | awk 'BEGIN{e=0;c=-1}c&&--c;/error/{if (!e) {c=30;e=1}};{if (!c) {exit 1}}'

    - stage: Pre-build-2
      script:
        - travis_long "timeout 2400 leanpkg test" | awk 'BEGIN{e=0;c=-1}c&&--c;/error/{if (!e) {c=30;e=1}};{if (!c) {exit 1}}'

    - stage: Test
      script:
        - leanpkg test
        - lean --recursive --export=mathlib.txt src/
        - leanchecker mathlib.txt

notifications:
  webhooks:
    - https://leanprover.zulipchat.com/api/v1/external/travis?stream=travis&topic=build-status&api_key=SwF1QzwUWol76dCxsYgwHbI6giN3cxGn
before_deploy:
     before_deploy:
      # Set up git user name and tag this commit
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
      - export ARCHIVE=mathlib-$TRAVIS_TAG.tar.gz
      - tar -zcvf $ARCHIVE.tar.gz src
      - git config --local user.name leanprover-mathlib-bot
      - git config --local user.email "$BOT_EMAIL"
      - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: HsAy78hjdJf+jg2yGqD7MWGCn+8K/EceaZ8sZ2U/95Kprmnetc1A5j1T0pgY531pQbjGm6XSbVdn0L0ymuunKo7gIfg3q4+ns6bMCucnxdCrXdJR9/DoUwSLVqJrdFjcigJ58ekMUh1l2g7jIfqJwCAM09FF+dMF09Wh9wVKGK1TYsr6RHZ7NqYlfme6hO+GwBw545NbSHxWEjvNT/8s+T8sMAwMWqjzXm/n/GNUn2TGoRwkwp/BdcQ9V7hKOHX0bbMQXc5RZniVqVnFpnZHx8zTIWJoKnx4HeS5beYN/OcPha6cShqpml3sGaGSUrkWBnQYOzcx28lA4jblYIc84g7lyryLhT2qYB02Fv4C97hyYIppDDdx4Op3NF4IdPqvHazji1pmctWH6muE0z/pJNw5fEX+eNY9djGnexRE8XnVUJigtvh0cUmYRPlb7+6Qza7K6lXzdXflK8TEDYcY9lTHoLw+h8ffFFxKq18yNzvwMoLk9VaA/h2gSCTTjOXrr8s3tLRBNJEjkFWvRAVPaJCbDep5DPf/eK9VEL497xZAfe8YLf1CKlw1ynV7nNb5VB4dPoQFxak/76gDQT/po1l2c/QC4EJe02Degx0+0FG+e2MlY7k/uJb4qndVXdJZQE9DQty0IquHPU0KNISp+VVb7xanh26UtulE/0YdChI=
  file: "$ARCHIVE"
  on:
    repo: leanprover-community/mathlib
